/********************************************************************************
** Form generated from reading UI file 'mainscreen.ui'
**
** Created by: Qt User Interface Compiler version 5.15.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_mainScreen
{
public:
    QWidget *centralwidget;
    QTabWidget *tabWidget;
    QWidget *ads;
    QLabel *label_15;
    QLabel *gifAd;
    QWidget *rewards;
    QLabel *greetings;
    QLabel *points;
    QLabel *label_17;
    QPushButton *freeDrink;
    QPushButton *freeSide;
    QPushButton *freeBurger;
    QPushButton *freeCombo;
    QPushButton *freeMask;
    QLabel *pts1;
    QLabel *pts2;
    QLabel *pts3;
    QLabel *pts4;
    QLabel *pts5;
    QPushButton *cokeButton;
    QPushButton *spriteButton;
    QPushButton *waterButton;
    QPushButton *friesButton;
    QPushButton *chipsButton;
    QPushButton *burgerButton;
    QPushButton *cheeseButton;
    QPushButton *impButton;
    QPushButton *AButton;
    QPushButton *BButton;
    QPushButton *CButton;
    QPushButton *SButton;
    QPushButton *MButton;
    QPushButton *LButton;
    QLabel *directions;
    QWidget *update;
    QLabel *pic;
    QLabel *label_13;
    QLabel *name;
    QLabel *cost;
    QLabel *label_14;
    QLabel *description;
    QPushButton *right;
    QPushButton *left;
    QFrame *line_8;
    QFrame *line_9;
    QWidget *oderHist;
    QLabel *viewOrderLabel;
    QListWidget *orderList;
    QListWidget *priceList;
    QFrame *line1;
    QLabel *subTotalLabel;
    QLabel *taxLabel;
    QLabel *totalLabel;
    QLabel *OHsub;
    QLabel *OHtax;
    QLabel *OHtotal;
    QLabel *subDollarSign;
    QLabel *taxDollarSign;
    QLabel *totalDollarSign;
    QFrame *line2;
    QFrame *line_17;
    QLabel *label_32;
    QPushButton *viewOrderB;
    QLabel *OHlabel;
    QLabel *VOLabel;
    QListWidget *orderhistory;
    QWidget *menu;
    QLabel *burger;
    QLabel *cheese;
    QLabel *impossible;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *fries;
    QLabel *chips;
    QLabel *label_5;
    QLabel *coke;
    QLabel *water;
    QLabel *sprite;
    QLabel *label_6;
    QLabel *Burger1;
    QLabel *Burger1Price;
    QLabel *Burger1Des;
    QPushButton *addBurger1;
    QLabel *Burger2;
    QLabel *Burger2Price;
    QLabel *Burger2Des;
    QPushButton *addBurger2;
    QPushButton *addBurger3;
    QLabel *Burger3;
    QLabel *Burger3Price;
    QLabel *Burger3Des;
    QPushButton *cokeB;
    QPushButton *spriteB;
    QPushButton *waterB;
    QLabel *label;
    QLabel *fries1;
    QLabel *fries1Price;
    QLabel *fries1Des;
    QPushButton *addFries;
    QPushButton *addChips;
    QLabel *chips1;
    QLabel *chips1Price;
    QLabel *chips1Des;
    QLabel *combo1;
    QLabel *combo2;
    QLabel *combo3;
    QLabel *combo1Des;
    QLabel *combo2Des;
    QLabel *combo3Des;
    QPushButton *comboA;
    QPushButton *comboB;
    QPushButton *comboC;
    QLabel *combo1Price;
    QLabel *combo2Price;
    QLabel *combo3Price;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QLabel *message;
    QWidget *cart;
    QLabel *label_2;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *subtotal;
    QLabel *tax;
    QLabel *total;
    QFrame *line_5;
    QPushButton *completeOrder;
    QFrame *line_6;
    QFrame *line_7;
    QLabel *makingOrder;
    QProgressBar *progressBar;
    QLabel *progress;
    QLabel *estTime;
    QPushButton *orderReceived;
    QLabel *hourLimit;
    QLabel *timer;
    QLabel *timeUnit;
    QLabel *timeRemain;
    QPushButton *end;
    QListWidget *listWidget;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QListWidget *listWidget2;
    QListWidget *remove;
    QLabel *notify;
    QLabel *notify2;
    QPushButton *cancelOrder;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *mainScreen)
    {
        if (mainScreen->objectName().isEmpty())
            mainScreen->setObjectName(QString::fromUtf8("mainScreen"));
        mainScreen->resize(659, 453);
        centralwidget = new QWidget(mainScreen);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 1, 661, 931));
        ads = new QWidget();
        ads->setObjectName(QString::fromUtf8("ads"));
        label_15 = new QLabel(ads);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(70, 10, 511, 51));
        label_15->setFrameShape(QFrame::Box);
        label_15->setFrameShadow(QFrame::Plain);
        label_15->setLineWidth(5);
        gifAd = new QLabel(ads);
        gifAd->setObjectName(QString::fromUtf8("gifAd"));
        gifAd->setGeometry(QRect(40, 80, 571, 261));
        tabWidget->addTab(ads, QString());
        rewards = new QWidget();
        rewards->setObjectName(QString::fromUtf8("rewards"));
        greetings = new QLabel(rewards);
        greetings->setObjectName(QString::fromUtf8("greetings"));
        greetings->setGeometry(QRect(30, 10, 101, 21));
        greetings->setFrameShape(QFrame::Box);
        greetings->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        points = new QLabel(rewards);
        points->setObjectName(QString::fromUtf8("points"));
        points->setGeometry(QRect(470, 10, 131, 20));
        points->setFrameShape(QFrame::Box);
        label_17 = new QLabel(rewards);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(190, 10, 241, 31));
        label_17->setFrameShape(QFrame::Box);
        label_17->setLineWidth(2);
        label_17->setAlignment(Qt::AlignCenter);
        freeDrink = new QPushButton(rewards);
        freeDrink->setObjectName(QString::fromUtf8("freeDrink"));
        freeDrink->setGeometry(QRect(70, 80, 211, 51));
        freeSide = new QPushButton(rewards);
        freeSide->setObjectName(QString::fromUtf8("freeSide"));
        freeSide->setGeometry(QRect(70, 140, 211, 51));
        freeBurger = new QPushButton(rewards);
        freeBurger->setObjectName(QString::fromUtf8("freeBurger"));
        freeBurger->setGeometry(QRect(70, 200, 211, 51));
        freeCombo = new QPushButton(rewards);
        freeCombo->setObjectName(QString::fromUtf8("freeCombo"));
        freeCombo->setGeometry(QRect(70, 260, 211, 51));
        freeMask = new QPushButton(rewards);
        freeMask->setObjectName(QString::fromUtf8("freeMask"));
        freeMask->setGeometry(QRect(70, 320, 211, 51));
        pts1 = new QLabel(rewards);
        pts1->setObjectName(QString::fromUtf8("pts1"));
        pts1->setGeometry(QRect(20, 80, 47, 41));
        pts1->setAlignment(Qt::AlignCenter);
        pts2 = new QLabel(rewards);
        pts2->setObjectName(QString::fromUtf8("pts2"));
        pts2->setGeometry(QRect(20, 140, 47, 41));
        pts2->setAlignment(Qt::AlignCenter);
        pts3 = new QLabel(rewards);
        pts3->setObjectName(QString::fromUtf8("pts3"));
        pts3->setGeometry(QRect(20, 200, 47, 51));
        pts3->setAlignment(Qt::AlignCenter);
        pts4 = new QLabel(rewards);
        pts4->setObjectName(QString::fromUtf8("pts4"));
        pts4->setGeometry(QRect(20, 260, 47, 51));
        pts4->setAlignment(Qt::AlignCenter);
        pts5 = new QLabel(rewards);
        pts5->setObjectName(QString::fromUtf8("pts5"));
        pts5->setGeometry(QRect(20, 320, 47, 51));
        pts5->setAlignment(Qt::AlignCenter);
        cokeButton = new QPushButton(rewards);
        cokeButton->setObjectName(QString::fromUtf8("cokeButton"));
        cokeButton->setGeometry(QRect(320, 90, 75, 23));
        spriteButton = new QPushButton(rewards);
        spriteButton->setObjectName(QString::fromUtf8("spriteButton"));
        spriteButton->setGeometry(QRect(430, 90, 75, 23));
        waterButton = new QPushButton(rewards);
        waterButton->setObjectName(QString::fromUtf8("waterButton"));
        waterButton->setGeometry(QRect(540, 90, 75, 23));
        friesButton = new QPushButton(rewards);
        friesButton->setObjectName(QString::fromUtf8("friesButton"));
        friesButton->setGeometry(QRect(320, 150, 75, 23));
        chipsButton = new QPushButton(rewards);
        chipsButton->setObjectName(QString::fromUtf8("chipsButton"));
        chipsButton->setGeometry(QRect(430, 150, 75, 23));
        burgerButton = new QPushButton(rewards);
        burgerButton->setObjectName(QString::fromUtf8("burgerButton"));
        burgerButton->setGeometry(QRect(320, 210, 75, 23));
        cheeseButton = new QPushButton(rewards);
        cheeseButton->setObjectName(QString::fromUtf8("cheeseButton"));
        cheeseButton->setGeometry(QRect(430, 210, 75, 23));
        impButton = new QPushButton(rewards);
        impButton->setObjectName(QString::fromUtf8("impButton"));
        impButton->setGeometry(QRect(540, 210, 75, 23));
        AButton = new QPushButton(rewards);
        AButton->setObjectName(QString::fromUtf8("AButton"));
        AButton->setGeometry(QRect(320, 270, 75, 23));
        BButton = new QPushButton(rewards);
        BButton->setObjectName(QString::fromUtf8("BButton"));
        BButton->setGeometry(QRect(430, 270, 75, 23));
        CButton = new QPushButton(rewards);
        CButton->setObjectName(QString::fromUtf8("CButton"));
        CButton->setGeometry(QRect(540, 270, 75, 23));
        SButton = new QPushButton(rewards);
        SButton->setObjectName(QString::fromUtf8("SButton"));
        SButton->setGeometry(QRect(320, 330, 75, 23));
        MButton = new QPushButton(rewards);
        MButton->setObjectName(QString::fromUtf8("MButton"));
        MButton->setGeometry(QRect(430, 330, 75, 23));
        LButton = new QPushButton(rewards);
        LButton->setObjectName(QString::fromUtf8("LButton"));
        LButton->setGeometry(QRect(540, 330, 75, 23));
        directions = new QLabel(rewards);
        directions->setObjectName(QString::fromUtf8("directions"));
        directions->setGeometry(QRect(70, 50, 541, 16));
        directions->setAlignment(Qt::AlignCenter);
        tabWidget->addTab(rewards, QString());
        update = new QWidget();
        update->setObjectName(QString::fromUtf8("update"));
        pic = new QLabel(update);
        pic->setObjectName(QString::fromUtf8("pic"));
        pic->setGeometry(QRect(180, 110, 271, 191));
        label_13 = new QLabel(update);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(130, 10, 371, 41));
        label_13->setFrameShape(QFrame::Box);
        label_13->setLineWidth(3);
        label_13->setAlignment(Qt::AlignCenter);
        name = new QLabel(update);
        name->setObjectName(QString::fromUtf8("name"));
        name->setGeometry(QRect(180, 70, 171, 20));
        cost = new QLabel(update);
        cost->setObjectName(QString::fromUtf8("cost"));
        cost->setGeometry(QRect(430, 70, 51, 20));
        label_14 = new QLabel(update);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(400, 70, 20, 21));
        label_14->setAlignment(Qt::AlignCenter);
        description = new QLabel(update);
        description->setObjectName(QString::fromUtf8("description"));
        description->setGeometry(QRect(180, 320, 271, 41));
        right = new QPushButton(update);
        right->setObjectName(QString::fromUtf8("right"));
        right->setGeometry(QRect(460, 110, 31, 191));
        left = new QPushButton(update);
        left->setObjectName(QString::fromUtf8("left"));
        left->setGeometry(QRect(140, 110, 31, 191));
        line_8 = new QFrame(update);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(180, 300, 271, 20));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(update);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(180, 90, 271, 20));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        tabWidget->addTab(update, QString());
        oderHist = new QWidget();
        oderHist->setObjectName(QString::fromUtf8("oderHist"));
        viewOrderLabel = new QLabel(oderHist);
        viewOrderLabel->setObjectName(QString::fromUtf8("viewOrderLabel"));
        viewOrderLabel->setGeometry(QRect(360, 10, 251, 31));
        viewOrderLabel->setLayoutDirection(Qt::LeftToRight);
        viewOrderLabel->setFrameShape(QFrame::Box);
        viewOrderLabel->setAlignment(Qt::AlignCenter);
        orderList = new QListWidget(oderHist);
        orderList->setObjectName(QString::fromUtf8("orderList"));
        orderList->setGeometry(QRect(340, 80, 231, 191));
        orderList->setLayoutDirection(Qt::LeftToRight);
        orderList->setItemAlignment(Qt::AlignJustify);
        priceList = new QListWidget(oderHist);
        priceList->setObjectName(QString::fromUtf8("priceList"));
        priceList->setGeometry(QRect(570, 80, 61, 191));
        priceList->setLayoutDirection(Qt::LeftToRight);
        priceList->setItemAlignment(Qt::AlignJustify|Qt::AlignRight|Qt::AlignTrailing);
        line1 = new QFrame(oderHist);
        line1->setObjectName(QString::fromUtf8("line1"));
        line1->setGeometry(QRect(350, 270, 271, 16));
        line1->setFrameShape(QFrame::HLine);
        line1->setFrameShadow(QFrame::Sunken);
        subTotalLabel = new QLabel(oderHist);
        subTotalLabel->setObjectName(QString::fromUtf8("subTotalLabel"));
        subTotalLabel->setGeometry(QRect(360, 280, 51, 16));
        taxLabel = new QLabel(oderHist);
        taxLabel->setObjectName(QString::fromUtf8("taxLabel"));
        taxLabel->setGeometry(QRect(360, 300, 51, 16));
        totalLabel = new QLabel(oderHist);
        totalLabel->setObjectName(QString::fromUtf8("totalLabel"));
        totalLabel->setGeometry(QRect(360, 320, 51, 16));
        OHsub = new QLabel(oderHist);
        OHsub->setObjectName(QString::fromUtf8("OHsub"));
        OHsub->setGeometry(QRect(560, 280, 61, 16));
        OHsub->setLayoutDirection(Qt::LeftToRight);
        OHsub->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        OHtax = new QLabel(oderHist);
        OHtax->setObjectName(QString::fromUtf8("OHtax"));
        OHtax->setGeometry(QRect(560, 300, 61, 16));
        OHtax->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        OHtotal = new QLabel(oderHist);
        OHtotal->setObjectName(QString::fromUtf8("OHtotal"));
        OHtotal->setGeometry(QRect(560, 320, 61, 16));
        OHtotal->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        subDollarSign = new QLabel(oderHist);
        subDollarSign->setObjectName(QString::fromUtf8("subDollarSign"));
        subDollarSign->setGeometry(QRect(540, 280, 16, 16));
        subDollarSign->setAlignment(Qt::AlignCenter);
        taxDollarSign = new QLabel(oderHist);
        taxDollarSign->setObjectName(QString::fromUtf8("taxDollarSign"));
        taxDollarSign->setGeometry(QRect(540, 300, 16, 16));
        taxDollarSign->setAlignment(Qt::AlignCenter);
        totalDollarSign = new QLabel(oderHist);
        totalDollarSign->setObjectName(QString::fromUtf8("totalDollarSign"));
        totalDollarSign->setGeometry(QRect(540, 320, 16, 16));
        totalDollarSign->setAlignment(Qt::AlignCenter);
        line2 = new QFrame(oderHist);
        line2->setObjectName(QString::fromUtf8("line2"));
        line2->setGeometry(QRect(350, 330, 271, 16));
        line2->setFrameShape(QFrame::HLine);
        line2->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(oderHist);
        line_17->setObjectName(QString::fromUtf8("line_17"));
        line_17->setGeometry(QRect(310, 10, 16, 351));
        line_17->setFrameShape(QFrame::VLine);
        line_17->setFrameShadow(QFrame::Sunken);
        label_32 = new QLabel(oderHist);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(30, 10, 251, 31));
        label_32->setLayoutDirection(Qt::LeftToRight);
        label_32->setFrameShape(QFrame::Box);
        label_32->setAlignment(Qt::AlignCenter);
        viewOrderB = new QPushButton(oderHist);
        viewOrderB->setObjectName(QString::fromUtf8("viewOrderB"));
        viewOrderB->setGeometry(QRect(34, 280, 251, 31));
        OHlabel = new QLabel(oderHist);
        OHlabel->setObjectName(QString::fromUtf8("OHlabel"));
        OHlabel->setGeometry(QRect(30, 50, 251, 20));
        OHlabel->setAlignment(Qt::AlignCenter);
        VOLabel = new QLabel(oderHist);
        VOLabel->setObjectName(QString::fromUtf8("VOLabel"));
        VOLabel->setGeometry(QRect(360, 50, 251, 20));
        orderhistory = new QListWidget(oderHist);
        orderhistory->setObjectName(QString::fromUtf8("orderhistory"));
        orderhistory->setGeometry(QRect(30, 80, 256, 192));
        tabWidget->addTab(oderHist, QString());
        menu = new QWidget();
        menu->setObjectName(QString::fromUtf8("menu"));
        burger = new QLabel(menu);
        burger->setObjectName(QString::fromUtf8("burger"));
        burger->setGeometry(QRect(20, 50, 81, 61));
        cheese = new QLabel(menu);
        cheese->setObjectName(QString::fromUtf8("cheese"));
        cheese->setGeometry(QRect(20, 170, 81, 61));
        impossible = new QLabel(menu);
        impossible->setObjectName(QString::fromUtf8("impossible"));
        impossible->setGeometry(QRect(20, 290, 81, 61));
        label_3 = new QLabel(menu);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(30, 10, 171, 16));
        label_3->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(menu);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(230, 50, 191, 16));
        label_4->setAlignment(Qt::AlignCenter);
        fries = new QLabel(menu);
        fries->setObjectName(QString::fromUtf8("fries"));
        fries->setGeometry(QRect(440, 190, 61, 41));
        chips = new QLabel(menu);
        chips->setObjectName(QString::fromUtf8("chips"));
        chips->setGeometry(QRect(440, 310, 61, 41));
        label_5 = new QLabel(menu);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(440, 10, 191, 16));
        label_5->setAlignment(Qt::AlignCenter);
        coke = new QLabel(menu);
        coke->setObjectName(QString::fromUtf8("coke"));
        coke->setGeometry(QRect(440, 70, 51, 41));
        water = new QLabel(menu);
        water->setObjectName(QString::fromUtf8("water"));
        water->setGeometry(QRect(580, 70, 51, 41));
        sprite = new QLabel(menu);
        sprite->setObjectName(QString::fromUtf8("sprite"));
        sprite->setGeometry(QRect(510, 70, 51, 41));
        label_6 = new QLabel(menu);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(440, 160, 191, 16));
        label_6->setAlignment(Qt::AlignCenter);
        Burger1 = new QLabel(menu);
        Burger1->setObjectName(QString::fromUtf8("Burger1"));
        Burger1->setGeometry(QRect(20, 30, 91, 16));
        Burger1Price = new QLabel(menu);
        Burger1Price->setObjectName(QString::fromUtf8("Burger1Price"));
        Burger1Price->setGeometry(QRect(160, 30, 47, 13));
        Burger1Price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Burger1Des = new QLabel(menu);
        Burger1Des->setObjectName(QString::fromUtf8("Burger1Des"));
        Burger1Des->setGeometry(QRect(110, 50, 101, 41));
        Burger1Des->setWordWrap(true);
        addBurger1 = new QPushButton(menu);
        addBurger1->setObjectName(QString::fromUtf8("addBurger1"));
        addBurger1->setGeometry(QRect(20, 120, 191, 23));
        Burger2 = new QLabel(menu);
        Burger2->setObjectName(QString::fromUtf8("Burger2"));
        Burger2->setGeometry(QRect(20, 150, 91, 16));
        Burger2Price = new QLabel(menu);
        Burger2Price->setObjectName(QString::fromUtf8("Burger2Price"));
        Burger2Price->setGeometry(QRect(160, 150, 47, 13));
        Burger2Price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Burger2Des = new QLabel(menu);
        Burger2Des->setObjectName(QString::fromUtf8("Burger2Des"));
        Burger2Des->setGeometry(QRect(110, 170, 101, 41));
        Burger2Des->setWordWrap(true);
        addBurger2 = new QPushButton(menu);
        addBurger2->setObjectName(QString::fromUtf8("addBurger2"));
        addBurger2->setGeometry(QRect(20, 240, 191, 23));
        addBurger3 = new QPushButton(menu);
        addBurger3->setObjectName(QString::fromUtf8("addBurger3"));
        addBurger3->setGeometry(QRect(20, 360, 191, 23));
        Burger3 = new QLabel(menu);
        Burger3->setObjectName(QString::fromUtf8("Burger3"));
        Burger3->setGeometry(QRect(20, 270, 111, 16));
        Burger3Price = new QLabel(menu);
        Burger3Price->setObjectName(QString::fromUtf8("Burger3Price"));
        Burger3Price->setGeometry(QRect(160, 270, 47, 13));
        Burger3Price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Burger3Des = new QLabel(menu);
        Burger3Des->setObjectName(QString::fromUtf8("Burger3Des"));
        Burger3Des->setGeometry(QRect(110, 290, 101, 41));
        Burger3Des->setWordWrap(true);
        cokeB = new QPushButton(menu);
        cokeB->setObjectName(QString::fromUtf8("cokeB"));
        cokeB->setGeometry(QRect(434, 120, 61, 23));
        spriteB = new QPushButton(menu);
        spriteB->setObjectName(QString::fromUtf8("spriteB"));
        spriteB->setGeometry(QRect(500, 120, 61, 23));
        waterB = new QPushButton(menu);
        waterB->setObjectName(QString::fromUtf8("waterB"));
        waterB->setGeometry(QRect(570, 120, 61, 23));
        label = new QLabel(menu);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(466, 30, 141, 21));
        label->setAlignment(Qt::AlignCenter);
        fries1 = new QLabel(menu);
        fries1->setObjectName(QString::fromUtf8("fries1"));
        fries1->setGeometry(QRect(440, 170, 91, 16));
        fries1Price = new QLabel(menu);
        fries1Price->setObjectName(QString::fromUtf8("fries1Price"));
        fries1Price->setGeometry(QRect(580, 170, 47, 13));
        fries1Price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fries1Des = new QLabel(menu);
        fries1Des->setObjectName(QString::fromUtf8("fries1Des"));
        fries1Des->setGeometry(QRect(530, 190, 101, 41));
        fries1Des->setWordWrap(true);
        addFries = new QPushButton(menu);
        addFries->setObjectName(QString::fromUtf8("addFries"));
        addFries->setGeometry(QRect(440, 240, 191, 23));
        addChips = new QPushButton(menu);
        addChips->setObjectName(QString::fromUtf8("addChips"));
        addChips->setGeometry(QRect(440, 360, 191, 23));
        chips1 = new QLabel(menu);
        chips1->setObjectName(QString::fromUtf8("chips1"));
        chips1->setGeometry(QRect(440, 290, 91, 16));
        chips1Price = new QLabel(menu);
        chips1Price->setObjectName(QString::fromUtf8("chips1Price"));
        chips1Price->setGeometry(QRect(580, 290, 47, 13));
        chips1Price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chips1Des = new QLabel(menu);
        chips1Des->setObjectName(QString::fromUtf8("chips1Des"));
        chips1Des->setGeometry(QRect(530, 300, 101, 51));
        chips1Des->setWordWrap(true);
        combo1 = new QLabel(menu);
        combo1->setObjectName(QString::fromUtf8("combo1"));
        combo1->setGeometry(QRect(230, 70, 71, 16));
        combo1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        combo2 = new QLabel(menu);
        combo2->setObjectName(QString::fromUtf8("combo2"));
        combo2->setGeometry(QRect(230, 190, 71, 16));
        combo2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        combo3 = new QLabel(menu);
        combo3->setObjectName(QString::fromUtf8("combo3"));
        combo3->setGeometry(QRect(230, 310, 71, 16));
        combo3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        combo1Des = new QLabel(menu);
        combo1Des->setObjectName(QString::fromUtf8("combo1Des"));
        combo1Des->setGeometry(QRect(230, 90, 191, 31));
        combo1Des->setTextFormat(Qt::AutoText);
        combo1Des->setWordWrap(true);
        combo2Des = new QLabel(menu);
        combo2Des->setObjectName(QString::fromUtf8("combo2Des"));
        combo2Des->setGeometry(QRect(230, 210, 191, 31));
        combo2Des->setTextFormat(Qt::AutoText);
        combo2Des->setWordWrap(true);
        combo3Des = new QLabel(menu);
        combo3Des->setObjectName(QString::fromUtf8("combo3Des"));
        combo3Des->setGeometry(QRect(230, 330, 191, 31));
        combo3Des->setTextFormat(Qt::AutoText);
        combo3Des->setWordWrap(true);
        comboA = new QPushButton(menu);
        comboA->setObjectName(QString::fromUtf8("comboA"));
        comboA->setGeometry(QRect(230, 120, 191, 23));
        comboB = new QPushButton(menu);
        comboB->setObjectName(QString::fromUtf8("comboB"));
        comboB->setGeometry(QRect(230, 240, 191, 23));
        comboC = new QPushButton(menu);
        comboC->setObjectName(QString::fromUtf8("comboC"));
        comboC->setGeometry(QRect(230, 360, 191, 23));
        combo1Price = new QLabel(menu);
        combo1Price->setObjectName(QString::fromUtf8("combo1Price"));
        combo1Price->setGeometry(QRect(370, 70, 47, 13));
        combo1Price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        combo2Price = new QLabel(menu);
        combo2Price->setObjectName(QString::fromUtf8("combo2Price"));
        combo2Price->setGeometry(QRect(370, 190, 47, 16));
        combo2Price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        combo3Price = new QLabel(menu);
        combo3Price->setObjectName(QString::fromUtf8("combo3Price"));
        combo3Price->setGeometry(QRect(370, 310, 47, 13));
        combo3Price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        line = new QFrame(menu);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(212, 10, 21, 371));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(menu);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(420, 10, 21, 371));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(menu);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(440, 150, 201, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(menu);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(230, 40, 191, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        message = new QLabel(menu);
        message->setObjectName(QString::fromUtf8("message"));
        message->setGeometry(QRect(230, 20, 191, 16));
        message->setAlignment(Qt::AlignCenter);
        tabWidget->addTab(menu, QString());
        cart = new QWidget();
        cart->setObjectName(QString::fromUtf8("cart"));
        label_2 = new QLabel(cart);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(40, 20, 251, 31));
        label_2->setLayoutDirection(Qt::LeftToRight);
        label_2->setFrameShape(QFrame::Box);
        label_2->setAlignment(Qt::AlignCenter);
        label_7 = new QLabel(cart);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(70, 280, 51, 16));
        label_8 = new QLabel(cart);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(70, 300, 51, 16));
        label_9 = new QLabel(cart);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(70, 320, 51, 16));
        subtotal = new QLabel(cart);
        subtotal->setObjectName(QString::fromUtf8("subtotal"));
        subtotal->setGeometry(QRect(260, 280, 61, 16));
        subtotal->setLayoutDirection(Qt::LeftToRight);
        subtotal->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tax = new QLabel(cart);
        tax->setObjectName(QString::fromUtf8("tax"));
        tax->setGeometry(QRect(260, 300, 61, 16));
        tax->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        total = new QLabel(cart);
        total->setObjectName(QString::fromUtf8("total"));
        total->setGeometry(QRect(260, 320, 61, 16));
        total->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        line_5 = new QFrame(cart);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(60, 270, 271, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        completeOrder = new QPushButton(cart);
        completeOrder->setObjectName(QString::fromUtf8("completeOrder"));
        completeOrder->setGeometry(QRect(70, 350, 251, 23));
        line_6 = new QFrame(cart);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setGeometry(QRect(60, 330, 271, 16));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(cart);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(370, 20, 16, 351));
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        makingOrder = new QLabel(cart);
        makingOrder->setObjectName(QString::fromUtf8("makingOrder"));
        makingOrder->setGeometry(QRect(390, 20, 251, 31));
        makingOrder->setLayoutDirection(Qt::LeftToRight);
        makingOrder->setFrameShape(QFrame::Box);
        makingOrder->setAlignment(Qt::AlignCenter);
        progressBar = new QProgressBar(cart);
        progressBar->setObjectName(QString::fromUtf8("progressBar"));
        progressBar->setGeometry(QRect(390, 80, 251, 23));
        progressBar->setValue(24);
        progress = new QLabel(cart);
        progress->setObjectName(QString::fromUtf8("progress"));
        progress->setGeometry(QRect(390, 60, 211, 16));
        estTime = new QLabel(cart);
        estTime->setObjectName(QString::fromUtf8("estTime"));
        estTime->setGeometry(QRect(390, 110, 221, 16));
        orderReceived = new QPushButton(cart);
        orderReceived->setObjectName(QString::fromUtf8("orderReceived"));
        orderReceived->setGeometry(QRect(390, 130, 251, 23));
        hourLimit = new QLabel(cart);
        hourLimit->setObjectName(QString::fromUtf8("hourLimit"));
        hourLimit->setGeometry(QRect(380, 230, 271, 20));
        hourLimit->setAlignment(Qt::AlignCenter);
        timer = new QLabel(cart);
        timer->setObjectName(QString::fromUtf8("timer"));
        timer->setGeometry(QRect(390, 270, 251, 51));
        timer->setFrameShape(QFrame::Box);
        timer->setLineWidth(5);
        timer->setMidLineWidth(0);
        timer->setAlignment(Qt::AlignCenter);
        timeUnit = new QLabel(cart);
        timeUnit->setObjectName(QString::fromUtf8("timeUnit"));
        timeUnit->setGeometry(QRect(390, 320, 241, 16));
        timeUnit->setAlignment(Qt::AlignCenter);
        timeRemain = new QLabel(cart);
        timeRemain->setObjectName(QString::fromUtf8("timeRemain"));
        timeRemain->setGeometry(QRect(380, 250, 251, 20));
        timeRemain->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        end = new QPushButton(cart);
        end->setObjectName(QString::fromUtf8("end"));
        end->setGeometry(QRect(390, 350, 251, 23));
        listWidget = new QListWidget(cart);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(10, 80, 231, 191));
        listWidget->setLayoutDirection(Qt::LeftToRight);
        listWidget->setItemAlignment(Qt::AlignJustify);
        label_10 = new QLabel(cart);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(240, 280, 16, 16));
        label_10->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(cart);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(240, 300, 16, 16));
        label_11->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(cart);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(240, 320, 16, 16));
        label_12->setAlignment(Qt::AlignCenter);
        listWidget2 = new QListWidget(cart);
        listWidget2->setObjectName(QString::fromUtf8("listWidget2"));
        listWidget2->setGeometry(QRect(240, 80, 61, 191));
        listWidget2->setLayoutDirection(Qt::LeftToRight);
        listWidget2->setItemAlignment(Qt::AlignJustify|Qt::AlignRight|Qt::AlignTrailing);
        remove = new QListWidget(cart);
        remove->setObjectName(QString::fromUtf8("remove"));
        remove->setGeometry(QRect(310, 80, 61, 191));
        remove->setLayoutDirection(Qt::LeftToRight);
        remove->setItemAlignment(Qt::AlignJustify);
        notify = new QLabel(cart);
        notify->setObjectName(QString::fromUtf8("notify"));
        notify->setGeometry(QRect(20, 60, 341, 21));
        notify->setAlignment(Qt::AlignCenter);
        notify2 = new QLabel(cart);
        notify2->setObjectName(QString::fromUtf8("notify2"));
        notify2->setGeometry(QRect(380, 190, 271, 20));
        notify2->setAlignment(Qt::AlignCenter);
        cancelOrder = new QPushButton(cart);
        cancelOrder->setObjectName(QString::fromUtf8("cancelOrder"));
        cancelOrder->setGeometry(QRect(390, 160, 251, 23));
        tabWidget->addTab(cart, QString());
        mainScreen->setCentralWidget(centralwidget);
        menubar = new QMenuBar(mainScreen);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 659, 21));
        mainScreen->setMenuBar(menubar);
        statusbar = new QStatusBar(mainScreen);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        mainScreen->setStatusBar(statusbar);

        retranslateUi(mainScreen);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(mainScreen);
    } // setupUi

    void retranslateUi(QMainWindow *mainScreen)
    {
        mainScreen->setWindowTitle(QCoreApplication::translate("mainScreen", "MainWindow", nullptr));
        label_15->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">WELCOME TO SUPERSONIC</span></p></body></html>", nullptr));
        gifAd->setText(QCoreApplication::translate("mainScreen", "TextLabel", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(ads), QCoreApplication::translate("mainScreen", "SPECIALS", nullptr));
        greetings->setText(QCoreApplication::translate("mainScreen", "WELCOME ANDY!", nullptr));
        points->setText(QCoreApplication::translate("mainScreen", "REWARDS POINTS:", nullptr));
        label_17->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">GET REWARDS</span></p></body></html>", nullptr));
        freeDrink->setText(QCoreApplication::translate("mainScreen", "FREE DRINK", nullptr));
        freeSide->setText(QCoreApplication::translate("mainScreen", "FREE SIDE", nullptr));
        freeBurger->setText(QCoreApplication::translate("mainScreen", "FREE BURGER", nullptr));
        freeCombo->setText(QCoreApplication::translate("mainScreen", "FREE COMBO", nullptr));
        freeMask->setText(QCoreApplication::translate("mainScreen", "FREE FACEMASK", nullptr));
        pts1->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">5 pts</span></p></body></html>", nullptr));
        pts2->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">15 pts</span></p></body></html>", nullptr));
        pts3->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">30 pts</span></p></body></html>", nullptr));
        pts4->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">50 pts</span></p></body></html>", nullptr));
        pts5->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">75 pts</span></p></body></html>", nullptr));
        cokeButton->setText(QCoreApplication::translate("mainScreen", "Coke", nullptr));
        spriteButton->setText(QCoreApplication::translate("mainScreen", "Sprite", nullptr));
        waterButton->setText(QCoreApplication::translate("mainScreen", "Water", nullptr));
        friesButton->setText(QCoreApplication::translate("mainScreen", "Fries", nullptr));
        chipsButton->setText(QCoreApplication::translate("mainScreen", "Chips", nullptr));
        burgerButton->setText(QCoreApplication::translate("mainScreen", "Burger", nullptr));
        cheeseButton->setText(QCoreApplication::translate("mainScreen", "Cheese", nullptr));
        impButton->setText(QCoreApplication::translate("mainScreen", "Impossible", nullptr));
        AButton->setText(QCoreApplication::translate("mainScreen", "A", nullptr));
        BButton->setText(QCoreApplication::translate("mainScreen", "B", nullptr));
        CButton->setText(QCoreApplication::translate("mainScreen", "C", nullptr));
        SButton->setText(QCoreApplication::translate("mainScreen", "S", nullptr));
        MButton->setText(QCoreApplication::translate("mainScreen", "M", nullptr));
        LButton->setText(QCoreApplication::translate("mainScreen", "L", nullptr));
        directions->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(rewards), QCoreApplication::translate("mainScreen", "REWARDS", nullptr));
        pic->setText(QCoreApplication::translate("mainScreen", "p", nullptr));
        label_13->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">CHECK OUT THE NEW ITEMS </span></p></body></html>", nullptr));
        name->setText(QCoreApplication::translate("mainScreen", "name", nullptr));
        cost->setText(QCoreApplication::translate("mainScreen", "price", nullptr));
        label_14->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        description->setText(QCoreApplication::translate("mainScreen", "description", nullptr));
        right->setText(QCoreApplication::translate("mainScreen", ">", nullptr));
        left->setText(QCoreApplication::translate("mainScreen", "<", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(update), QCoreApplication::translate("mainScreen", "UPDATES", nullptr));
        viewOrderLabel->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">VIEW ORDER</span></p></body></html>", nullptr));
        subTotalLabel->setText(QCoreApplication::translate("mainScreen", "SUBTOTAL", nullptr));
        taxLabel->setText(QCoreApplication::translate("mainScreen", "TAX", nullptr));
        totalLabel->setText(QCoreApplication::translate("mainScreen", "TOTAL", nullptr));
        OHsub->setText(QCoreApplication::translate("mainScreen", "0.00", nullptr));
        OHtax->setText(QCoreApplication::translate("mainScreen", "0.00", nullptr));
        OHtotal->setText(QCoreApplication::translate("mainScreen", "0.00", nullptr));
        subDollarSign->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        taxDollarSign->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        totalDollarSign->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        label_32->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">ORDER HISTORY</span></p></body></html>", nullptr));
        viewOrderB->setText(QCoreApplication::translate("mainScreen", "VIEW ORDER", nullptr));
        OHlabel->setText(QString());
        VOLabel->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(oderHist), QCoreApplication::translate("mainScreen", "ORDER HISTORY", nullptr));
        burger->setText(QCoreApplication::translate("mainScreen", "p1", nullptr));
        cheese->setText(QCoreApplication::translate("mainScreen", "p2", nullptr));
        impossible->setText(QCoreApplication::translate("mainScreen", "p3", nullptr));
        label_3->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">BURGERS</span></p></body></html>", nullptr));
        label_4->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">COMBOS</span></p></body></html>", nullptr));
        fries->setText(QCoreApplication::translate("mainScreen", "p4", nullptr));
        chips->setText(QCoreApplication::translate("mainScreen", "p5", nullptr));
        label_5->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">DRINKS</span></p></body></html>", nullptr));
        coke->setText(QCoreApplication::translate("mainScreen", "p5", nullptr));
        water->setText(QCoreApplication::translate("mainScreen", "p5", nullptr));
        sprite->setText(QCoreApplication::translate("mainScreen", "p5", nullptr));
        label_6->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">SIDES</span></p></body></html>", nullptr));
        Burger1->setText(QCoreApplication::translate("mainScreen", "NAME", nullptr));
        Burger1Price->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        addBurger1->setText(QCoreApplication::translate("mainScreen", "Select", nullptr));
        Burger2->setText(QCoreApplication::translate("mainScreen", "NAME", nullptr));
        Burger2Price->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        addBurger2->setText(QCoreApplication::translate("mainScreen", "Select", nullptr));
        addBurger3->setText(QCoreApplication::translate("mainScreen", "Select", nullptr));
        Burger3->setText(QCoreApplication::translate("mainScreen", "NAME", nullptr));
        Burger3Price->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        Burger3Des->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p>asdfasf s dfasd fas d sad fasdf asd sdf as</p></body></html>", nullptr));
        cokeB->setText(QCoreApplication::translate("mainScreen", "Coke", nullptr));
        spriteB->setText(QCoreApplication::translate("mainScreen", "Sprite", nullptr));
        waterB->setText(QCoreApplication::translate("mainScreen", "Water", nullptr));
        label->setText(QCoreApplication::translate("mainScreen", "ALL DRINKS ARE $1.50", nullptr));
        fries1->setText(QCoreApplication::translate("mainScreen", "NAME", nullptr));
        fries1Price->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        fries1Des->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p>asdfasf s dfasd fas d sad fasdf asd sdf as</p></body></html>", nullptr));
        addFries->setText(QCoreApplication::translate("mainScreen", "Select", nullptr));
        addChips->setText(QCoreApplication::translate("mainScreen", "Select", nullptr));
        chips1->setText(QCoreApplication::translate("mainScreen", "NAME", nullptr));
        chips1Price->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        chips1Des->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p>asdfasf s dfasd fas d sad fasdf asd sdf as</p></body></html>", nullptr));
        combo1->setText(QCoreApplication::translate("mainScreen", "NAME", nullptr));
        combo2->setText(QCoreApplication::translate("mainScreen", "NAME", nullptr));
        combo3->setText(QCoreApplication::translate("mainScreen", "NAME", nullptr));
        combo1Des->setText(QCoreApplication::translate("mainScreen", "TextLabel", nullptr));
        combo2Des->setText(QCoreApplication::translate("mainScreen", "TextLabel", nullptr));
        combo3Des->setText(QCoreApplication::translate("mainScreen", "TextLabel", nullptr));
        comboA->setText(QCoreApplication::translate("mainScreen", "COMBO A", nullptr));
        comboB->setText(QCoreApplication::translate("mainScreen", "COMBO B", nullptr));
        comboC->setText(QCoreApplication::translate("mainScreen", "COMBO C", nullptr));
        combo1Price->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        combo2Price->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        combo3Price->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        message->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(menu), QCoreApplication::translate("mainScreen", "MENU", nullptr));
        label_2->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">YOUR ORDER</span></p></body></html>", nullptr));
        label_7->setText(QCoreApplication::translate("mainScreen", "SUBTOTAL", nullptr));
        label_8->setText(QCoreApplication::translate("mainScreen", "TAX", nullptr));
        label_9->setText(QCoreApplication::translate("mainScreen", "TOTAL", nullptr));
        subtotal->setText(QCoreApplication::translate("mainScreen", "0.00", nullptr));
        tax->setText(QCoreApplication::translate("mainScreen", "0.00", nullptr));
        total->setText(QCoreApplication::translate("mainScreen", "0.00", nullptr));
        completeOrder->setText(QCoreApplication::translate("mainScreen", "COMPLETE ORDER", nullptr));
        makingOrder->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">MAKING YOUR ORDER NOW</span></p></body></html>", nullptr));
        progress->setText(QCoreApplication::translate("mainScreen", "<html><head/><body><p>IN PROGRESS</p></body></html>", nullptr));
        estTime->setText(QCoreApplication::translate("mainScreen", "ESTIMATED TIME: ~10 mins", nullptr));
        orderReceived->setText(QCoreApplication::translate("mainScreen", "I RECEIVED MY ORDER", nullptr));
        hourLimit->setText(QCoreApplication::translate("mainScreen", "YOU HAVE A 2 HOUR LIMIT TO EAT AT SUPERSONIC", nullptr));
        timer->setText(QCoreApplication::translate("mainScreen", "hr:min", nullptr));
        timeUnit->setText(QCoreApplication::translate("mainScreen", "HOUR:MINUTE", nullptr));
        timeRemain->setText(QCoreApplication::translate("mainScreen", "TIME REMAINING:", nullptr));
        end->setText(QCoreApplication::translate("mainScreen", "I HAVE LEFT SUPERSONIC", nullptr));
        label_10->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        label_11->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        label_12->setText(QCoreApplication::translate("mainScreen", "$", nullptr));
        notify->setText(QString());
        notify2->setText(QString());
        cancelOrder->setText(QCoreApplication::translate("mainScreen", "CANCEL MY ORDER", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(cart), QCoreApplication::translate("mainScreen", "CART", nullptr));
    } // retranslateUi

};

namespace Ui {
    class mainScreen: public Ui_mainScreen {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINSCREEN_H
